### ISSUE TITLE
saveFigure does not save the passed figure

### ISSUE THREAD

**Issue by jebej** [djoshea/matlab-save-figure#2]
Hello,
It seems that saveFigure saves the active figure, whether a figure handle is passed or not.

I'm assuming that this is because of the line `print('-dsvg', '-painters', file);`, which prints only the active figure.

This is a problem when opening many figures and trying to save them all at the end. A fix is to add the following somewhere before the print line:

``` matlab
% Make passed figure the current figure
set(0, 'CurrentFigure', hfig);
```

**Comment by jebej** [comment]
Actually a better option is to simply pass `hfig` to print:

``` matlab
print(hfig, '-dsvg', '-painters', file);
```

**Comment by djoshea** [comment]
Thanks! 523250a uses your second suggestion.
